#------------------------------------------------------------#
#     CI Build Configuration for master branch pre-release   #
#------------------------------------------------------------#
version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
environment:
  GITHUB_TOKEN:
    secure: tvoyJ/iv8Y+9VaKvOFvxegvQFBNqPkhiwghS8lQDsrt7B/1MWU4e8uOHQzfTU580
  priv_key:
    secure: dMxB7k2kJ20AJqhsDQyfo+ltMWiYa5Pi9pc2RfGNceNpgFYVu4koSh9J7Ei15W+fznJcMIC3fgY/Ozjb36BeX6l7Oq1GnfxAEwIaa/ZXAolJN6Drsam4Grsswd1cXxGM1VB++HX/9ipJtDI4vMgyP6YliL9hNDf2CuDk3uQ69JyGw/XQOmZwz/sk6COh+EOLODACd0n6WXScWyNML5U1Nmoiaxd47kSVXI8weHo5cZ/3CJi49/su3WQLMMGxIPAjNgpFVYhg2CZk8/IJrRvS4nTPTSG9rbg4y99ev5iKlVEQCgxMiAqGqApvVb4pqn4lj6ib84nyVMZbzxciWCdhCAt7ETYUA039p7vLf5MCZiDbIgbqW5WJwVUs8HkLpNXu2MiPvvVmUywQowlUpI51CQcRsJnPKSdxlFtedm0ygjvgIpX0afHAY/9Kmzq3xda+n2tTBOz7mbGKG4CFw/62sWH+uVAoHeb9pr4YudPKT6k36ZTgWTsYrbTL3g+b8452FMVz2sLyps/SSaHN7lgQpmW6r+HFAOg6WFZqat1e6OMC1s/haZa7WoC8dQpiJweSwGaFCQsNm+CC+M9k8xuNi1hNR4wB8/I+K71u7d4f2PzeLphI4MBDrmRMTwFsxfBky0lg+xS98w6Hhn2iiPmYoeGIoo10bs5QqR4YEvCIsRNZiJbuBJ0+2/qKZ/yzdzUcoeVQjSkeIQ68R0POR4Yb0JSUdY8UPESPcI4xBO0oRd9eCtrZfG3SP8DSTRmbuH06B/ewvn5h8DvC4S1bParoi7PnVWK8pJzjJ2Nkz83IMydD/1AUw0Xe5b/znyrJlEmOFpBeU+yfomJKEyAvVyrDhw1mcTcJFME7YvWljbdKxqf7XIhvnJl083Ax1hWve9b9yi2kvN1jN2XTaSYheuepH8gCNuj27PtXrP8ElKCVYgsrvzgQxnS91yW+4htvO7V6FYc3wDYQkniO5yAvznvxKrsPt8952pNZRa9+MjO0IW5pTR0e9SVCYJm5FSrygXq8qE9GYQC0LF+0RZV4bOepreTyKnCXQBOxUML8oowOWI2Dx7hmaibWsIwVT1vM7UI9V9tES9U4dunnZJVT4C3HUokCWyCtaXj5FIZuQI8Iua05ZThimcLsnQtwYp939a0EPcy/krvvoRQ/5uNSRngIe0pVmAPDJsGb6tBfIFGKkmmKPfdzb4qW62sE90YoELnDaC7OKqi3XuLgvoFmt/LSZTHZJZ7RO+eqGQR/au25qDphdVEWSmHK+84oWksM3S9rS9+jJFp021fqMd6x4sSsTc/hExUPaMoDgRzz/Vw9nqRO7/SBT2pvtDoOz0UZasNhByIhCyu6dNKAdcAL3k/LXKFYbEbYcskqegz+/XwFzyo6AJ9OM522ZAUnXVjf302+pPujVqkEr05Kqe6wnCkxOjpUEGvmxlcfC+HTlimNHySG8ez5EKPC4EJwf6ojHAiclfYrr3a0/SOrH97IX5l1zuu2Y/qYhaIZxWKP0vC6G+py3cDbjmSk75ROBGoGbrVFzaIiotgA4Ktst12LxjnDKV9yYpdN38uVk08fCWpLUHxPzuRXeqRJ/5aGUFaNU0aODe1b9W91Em7TxKpCNJzlwIDjNa/X6KneTH0a7cOHZyiq4Iy1hoEhkX5gv0rfa0SvagPl8GagwNpAZ55UcTp4S9NSqjNxdb1sxiwkUj+c0XK1JTEC1BImA2bKYvZgW5s/xbtBO2rQAlVLdi9HrjwRVDWrUzvNYyiEkAV5lAShPM8qR4i3MJ3QDMdtDBenb8ZFO4OKHB3FwJBorXJrX8zsEFMiNAYk46z0q3W+WgBJMKyqjkwQrASvrm2BDqsDjTPD58tNB456DLck0pCtkLHLS+CXSsp3zj/fGpHjhWxciSaoKfuO+O9TwpYuOl6NURbmr4rkhHPVPHJTQ922Dxc/hvDzuO0FTLxcCp63mENt0+mdmItrLVYn3VvtRP4QyCAYg/ULzC0rJGg2dG7LhWHs5TKemOIXGgnur6ZXOGsDJY/g+SX+6y3Nc+S2ff1YxyjCPOCbnMJWb5MIuchJgIM0BDxqLN07zDS69tL9X4o8n5mHZfXkJE9ILTe9sfThbiwGWnEXHn1qCLOkp0eFJOhKNFs0zt/hI5winijRRQfrHTo=
# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
build_script:
- ps: .\build.ps1
test: off
artifacts:
- path: '.\artifacts\**\*.nupkg'
deploy:
  - provider: NuGet
    name: Nuget feed
    on:
      #branch: master
      appveyor_repo_tag: true
    api_key:
      secure: 4ow9RfKvIn+10EJ4Hlry5LO73TnS0z4Nl0aAnL9xxhCoW0DAzwoQLTTJMRl4hT5L
    skip_symbols: false
    artifact: /.*\.nupkg/