#------------------------------------------------------------#
#     CI Build Configuration for master branch pre-release   #
#------------------------------------------------------------#
version: "{build}"
image: Visual Studio 2019
configuration: Release
environment:
  GITHUB_TOKEN:
    secure: DeB5HvTOAiL2ZPXX0pBBLd9BsJCIRMMXRpsvKQ4YRrGPZQ86TiT3y8VR6T7dPV6L
  NUGET_TOKEN:
    secure: hfNVh7FiNkQbrdCBKj7liVejvOTxG76WSp3gQ94ney664tmtJKYxV9EoHLtm/KiB
  APPVEYOR_TOKEN:
    secure: wVt1RgJAnhNTyIjtK9yFkQbEEM+fBk1TLUzo0j3pe2U=
# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
build_script:
- ps: .\build.ps1
test: off
